# Generated by Django 3.2.4 on 2021-06-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=255)),
                ('balance', models.IntegerField(default=0)),
                ('accountType', models.CharField(max_length=255)),
            ],
        ),
    ]
